- name: "Play Varaibles from Prompt"
  hosts: local
  connection: local
  vars_prompt:
    - name: "username"
      prompt: "Enter your username"
      private: false
    - name: "password"
      prompt: "Enter your password"
      private: true
  tasks:
    - name: "Display the input"
      ansible.builtin.debug:
        msg: "Username: {{ username }}, Password: {{ password }}"