- name: variables preference
  hosts: local
  connection: local
  vars:
    name: ansible from vars
  vars_files:
    - vars.yaml
  vars_prompt:
    - name: name
      prompt: "Enter your name"
      private: no
  tasks:
    - name: print the variable
      ansible.builtin.debug:
        msg: "The value variable comfing from {{ name }}"