- name: conditions
  hosts: local
  connection: local
  vars:
    my_var: "Hello, Ansible!"

  tasks:
    - name: when condition
      debug:
        msg: "This task will run only if the condition is true."
      when: my_var == "Hello!"