- name: demo on loop with installation of packages
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: Install multiple packages using loop
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - git
        - mongodb-org
      when: ansible_os_family == "RedHat"  #we can set condition using when OS family is RedHat