- name: "Accessing the dictionary and its elements from ansible"
  hosts: localhost
  connection: local
  became: true

  vars:
    details_map: #make sure not to use reserved keywords like dict or tags
      name: "DevOps with AWS Cloud"
      project: "learning devops"
      current_env: "ansible"
      learning_time: "4 months"

  tasks:
    - name: print the dictionary and its elements
      ansible.builtin.debug:
        msg: "Hi, Details follows: Name: {{ details_map.name }}, Project: {{ details_map.project }}, Current Environment: {{ details_map.current_env }}, Learning Time: {{ details_map.learning_time }}"
    
    - name: print the dictionary into list elements
      ansible.builtin.debug:
        msg: "Hi, Details follows: {{ details_map | dict2items }}"

    - name: set fact to convert dict to list      
      ansible.builtin.set_fact:
        details_list_output: "{{ details_map | dict2items }}"
    
    - name: print the list elements into dict again
      ansible.builtin.debug:
        msg: "Hi, Details follows: {{ details_list_output| items2dict }}"


# - name: print the list elements into dict
#   ansible.builtin.debug:
#     msg: "Hi, Details follows: {{ details_list_output.msg | items2dict }}"

# Hints to remember:

# You generally cannot directly use register keyword on a ansible.builtin.debug task because it contains metadata of entire data

# In this case, You should use "set_fact" keyword, it stores the actual data structure in a variable

# Each task can only have one module to use
